## YAML Template.
# app/services.yml
parameters:
    # ...   

services:
    validation:
        class: Nespresso\Validation
    nespresso.manager:
        class: Nespresso\Manager
    io:
        class: Nespresso\IO